language: ruby
rvm:
    - 1.9.3
env:
    - RAILS_ENV="test"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get install libqt4-dev libqtwebkit-dev
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:test:load
script: "bundle exec rspec spec/ --color --profile"
